apiVersion: "v1"
kind: "Service"
metadata:
  name: {{ print .Release.Name "-" .Values.toolboxType | quote }}
spec:
  selector:
    app: {{ print .Release.Name "-" .Values.toolboxType | quote }}
  clusterIP: "None"
  type: "ClusterIP"
